version: '3'
services:
  ethereum:
    image: trufflesuite/ganache-cli:v6.7.0
    command: --port=18545 --mnemonic="text fall reveal replace bonus combine swap goat air bonus submit repair"
    ports:
      - $ETHEREUM_RPC_PORT:18545
    networks:
      - testnet
  tests:
    build: .
    depends_on:
      - ethereum
    environment:
      ETHEREUM_RPC_TARGET: http://ethereum:18545
      VERBOSE: ${VERBOSE-}
    networks:
      - testnet

networks:
  testnet:
